name: 构建内核测试5.4
on:
  workflow_dispatch:
jobs:
  BuildKernel:
    env:
        GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
          
      - name: 下载依赖
        run: |
          sudo apt update
          sudo apt install -y \
          bc bison flex \
          libssl-dev \
          libelf-dev \
          libdw-dev \
          build-essential \
          lz4 \
          git \
          python3 \
          curl \
          dwarves \
          cpio \
          gcc-aarch64-linux-gnu

      - name: 克隆源码
        run: |
         git clone https://github.com/thofd/android_kernel_xiaomi_gauguin_5.4.294.git -b 14 --depth=1 kernel

      - name: 下载Clang GCC
        run: |
              wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/clang-r563880c.tar.gz    
              mkdir -p toolchains/clang-r563880c
              tar -xzf "clang-r563880c.tar.gz" -C "toolchains/clang-r563880c" || exit 1
              
              wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/android12L-release.tar.gz
              mkdir -p toolchains/aarch64-linux-android-4.9
              tar -xzf android12L-release.tar.gz -C toolchains/aarch64-linux-android-4.9
          
      - name: 制作内核config
        run: |
          cd ${GITHUB_WORKSPACE}/kernel
          export PATH="${GITHUB_WORKSPACE}/toolchains/clang-r563880c/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CROSS_COMPILE=aarch64-linux-gnu-
          export DROIDSPACES_CONFIG="vendor/droidspaces.config"

      - name: 构建内核
        run: |
          cd ${GITHUB_WORKSPACE}/kernel
          export PATH="${GITHUB_WORKSPACE}/toolchains/clang-r563880c/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CROSS_COMPILE=aarch64-linux-gnu-

          make O=out ARCH=arm64 gauguin_defconfig
          
          make -j$(nproc --all) ARCH=arm64 CC=clang LD=ld.lld HOSTCC=clang HOSTCXX=clang++ READELF=llvm-readelf HOSTAR=llvm-ar AR=llvm-ar AS=llvm-as NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip CROSS_COMPILE=aarch64-linux-gnu- 2>&1 | tee log.txt
      - name: 制作AK3
        run: |
          cd ${GITHUB_WORKSPACE}/kernel
          ZIP_NAME="gauguin_LineageOS-23.2_KernelSU_$(date -u +"%Y%m%d_%H%M")"
          
          git clone https://github.com/Kernel-SU/AnyKernel3.git || exit 1

          cp ${GITHUB_WORKSPACE}/kernel/arch/arm64/boot/Image AnyKernel3/Image
          cp ${GITHUB_WORKSPACE}/kernel/arch/arm64/boot/Image ./Image
          cd AnyKernel3 || exit 1

          sed -i "s|ksu_supported=true|ksu_supported=false|" anykernel.sh

          zip -r9 ../"${ZIP_NAME}.zip" * -x .git
          
      - name: 上传内核镜像
        uses: actions/upload-artifact@v4
        with:
            name: gauguin-kernel
            path: |
             ${GITHUB_WORKSPACE}/kernel/arch/arm64/boot/Image
             ${GITHUB_WORKSPACE}/kernel/build.log
