name: 构建内核
on:
  workflow_dispatch:
jobs:
  BuilsKernel:
    env:
        GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
          
      - name: 下载依赖
        run: |
          sudo apt update
          sudo apt install -y \
          bc bison flex \
          libssl-dev \
          libelf-dev \
          libdw-dev \
          build-essential \
          lz4 \
          git \
          python3 \
          curl \
          dwarves \
          cpio \
          gcc-aarch64-linux-gnu

      - name: 克隆源码
        run: |
         git clone https://github.com/LineageOS/android_kernel_xiaomi_gauguin -b lineage-23.2 --depth=1 gauguin

      - name: 下载Clang GCC
        run: |
              wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/clang-r563880c.tar.gz    
              mkdir -p toolchains/clang-r563880c
              tar -xzf "clang-r563880c.tar.gz" -C "toolchains/clang-r563880c" || exit 1
              
              wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/android12L-release.tar.gz
              mkdir -p toolchains/aarch64-linux-android-4.9
              tar -xzf android12L-release.tar.gz -C toolchains/aarch64-linux-android-4.9

      - name: 为内核加上KernelSU支持
        run: |   
              cd ${GITHUB_WORKSPACE}/gauguin
              wget https://raw.githubusercontent.com/backslashxx/KernelSU/refs/heads/master/kernel/setup.sh | bash -s master || exit 1

              curl -Lo patch2.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/non-GKI/02.fix_restore%20cgroup%20file%20prefix%20handling%20.patch || exit 1
              patch -p1 < patch2.patch
            
              cp ${GITHUB_WORKSPACE}/configs/droidspaces-nongki.config arch/arm64/configs/vendor/droidspaces.config

      - name: 制作内核config
        run: |
          sed -i 's/EXTRAVERSION = .*/EXTRAVERSION = -32457-DS-Lineage23.2/' ${GITHUB_WORKSPACE}/gauguin/Makefile
          cd ${GITHUB_WORKSPACE}/gauguin
          export PATH="${GITHUB_WORKSPACE}/toolchains/clang-r563880c/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CROSS_COMPILE=aarch64-linux-gnu-
          export DROIDSPACES_CONFIG="vendor/droidspaces.config"

            make O=out vendor/lito-perf_defconfig vendor/xiaomi/gauguin.config $DROIDSPACES_CONFIG

            echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=y" >> out/.config

      - name: 构建内核
        run: |
          cd ${GITHUB_WORKSPACE}/gauguin
          export PATH="${GITHUB_WORKSPACE}/toolchains/clang-r563880c/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CROSS_COMPILE=aarch64-linux-gnu-

          make -j$(nproc) O=out Image 2>&1 | tee ${GITHUB_WORKSPACE}/build.log

      - name: 制作AK3
        run: |
          cd ${GITHUB_WORKSPACE}/gauguin
          ZIP_NAME="gauguin_LineageOS-23.2_KernelSU_$(date -u +"%Y%m%d_%H%M")"
          
          git clone https://github.com/Kernel-SU/AnyKernel3.git || exit 1

          cp ~/gauguin/out/arch/arm64/boot/Image AnyKernel3/Image
          cp ~/gauguin/out/arch/arm64/boot/Image ./Image
          cd AnyKernel3 || exit 1

          sed -i "s|ksu_supported=true|" anykernel.sh

          zip -r9 ../"${ZIP_NAME}.zip" * -x .git
          
      - name: 发行
        run: |
          REL_NAME="gauguin_LineageOS-23.2_KernelSU_$(date -u +"%Y%m%d_%H%M")"
          cd ${GITHUB_WORKSPACE} || exit 1
          ZIP_FILE=$(ls *.zip)
          gh release create "$REL_NAME" --title "$REL_NAME" --notes "" "${ZIP_FILE}" Image build.log
