name: Build UEFI Shell

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EDK2
        run: |
          git clone https://github.com/tianocore/edk2.git
          cd edk2
          git submodule update --init --recursive
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential uuid-dev nasm \
            gcc-aarch64-linux-gnu python3
      
      - name: Build UEFI Shell
        run: |
          cd edk2
          export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
          make -C BaseTools
          . edksetup.sh
          build -a AARCH64 -p ShellPkg/ShellPkg.dsc -b RELEASE -t GCC5
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UEFI-Shell
          path: edk2/Build/Shell/RELEASE_GCC5/AARCH64/Shell.efi
